FROM bitnami/kafka:3.4.1

ENV ALLOW_PLAINTEXT_LISTENER=yes
ENV KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
ENV KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,EXTERNAL://:29092
ENV KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://${KAFKA_ADVERTISED_HOST:-localhost}:29092
ENV KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
ENV KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
ENV KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
ENV KAFKA_CFG_LOG_RETENTION_HOURS=24
ENV KAFKA_CFG_LOG_DIRS=/opt/bitnami/kafka/data
ENV KAFKA_HEAP_OPTS="-Xmx512m -Xms256m"

EXPOSE 9092 29092