[build]
builder = "DOCKERFILE"
dockerfilePath = "docker-compose.yml"
buildCommand = "docker-compose build"

[deploy]
startCommand = "docker-compose up -d"
healthcheckPath = "/actuator/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[scaling]
minInstances = 1
maxInstances = 1
memoryLimit = "2048M"

[env]
KAFKA_ADVERTISED_HOST = "${RAILWAY_PUBLIC_DOMAIN}"
KAFKA_LOG_RETENTION_HOURS = "24"