[build]
builder = "NIXPACKS"
nixpacksConfigPath = "nixpacks.toml"

[deploy]
startCommand = "cd kafka && docker build -t kafka . && cd ../zookeeper && docker build -t zookeeper . && cd .. && docker-compose up -d"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[scaling]
minInstances = 1
maxInstances = 1
memoryLimit = "2048M"

[env]
KAFKA_ADVERTISED_HOST = "${RAILWAY_PUBLIC_DOMAIN}"
KAFKA_LOG_RETENTION_HOURS = "24"