# Configuration Railway pour le déploiement de Kafka + Zookeeper

[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

# Configuration des ressources
[scaling]
minInstances = 1
maxInstances = 1
memoryLimit = "2048M"

# Configuration des variables d'environnement
[env]
KAFKA_ADVERTISED_HOST = "${RAILWAY_PUBLIC_DOMAIN}"
KAFKA_LOG_RETENTION_HOURS = "24"

# Configuration des volumes Railway
# Ces volumes doivent être créés via l'interface Railway
# ou en utilisant la CLI Railway
[mounts]
source = "kafka_zookeeper_data"
destination = "/app/data"