version: '3.8'

services:
  init-topics:
    image: bitnami/kafka:3.4.1
    depends_on:
      - kafka
    command: >
      bash -c "
        echo 'Waiting for Kafka to be ready...' &&
        sleep 30 &&
        kafka-topics.sh --bootstrap-server kafka:9092 --create --if-not-exists --topic authentication-events --partitions 3 --replication-factor 1 &&
        kafka-topics.sh --bootstrap-server kafka:9092 --create --if-not-exists --topic user-events --partitions 3 --replication-factor 1 &&
        kafka-topics.sh --bootstrap-server kafka:9092 --create --if-not-exists --topic notification-events --partitions 3 --replication-factor 1 &&
        kafka-topics.sh --bootstrap-server kafka:9092 --create --if-not-exists --topic map-events --partitions 3 --replication-factor 1 &&
        kafka-topics.sh --bootstrap-server kafka:9092 --create --if-not-exists --topic incident-events --partitions 3 --replication-factor 1 &&
        kafka-topics.sh --bootstrap-server kafka:9092 --create --if-not-exists --topic contact-events --partitions 3 --replication-factor 1 &&
        echo 'All topics created successfully!'
      "
    restart: on-failure